import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';

class ExportService {

  Future<void> exportExpensesToPDF(
      List<QueryDocumentSnapshot> expenses,
      double monthlyBudget,
      ) async {

    final pdf = pw.Document();

    // ✅ LOAD UNICODE FONT (Fix for ₹ symbol)
    final font = await PdfGoogleFonts.robotoRegular();

    final now = DateTime.now();
    final monthName = DateFormat('MMMM yyyy').format(now);
    final generatedDate = DateFormat('dd MMM yyyy').format(now);

    // SORT TRANSACTIONS BY DATE (Latest First)
    expenses.sort((a, b) {
      final dateA = (a['date'] as Timestamp).toDate();
      final dateB = (b['date'] as Timestamp).toDate();
      return dateB.compareTo(dateA);
    });

    double totalSpent = 0;

    for (var e in expenses) {
      totalSpent += (e['amount'] as num).toDouble();
    }

    double savings = monthlyBudget - totalSpent;

    int totalTransactions = expenses.length;

    // FIND TOP SPENDING CATEGORY
    Map<String, double> categoryTotals = {};

    for (var e in expenses) {
      String category = e['category'];
      double amount = (e['amount'] as num).toDouble();

      categoryTotals[category] = (categoryTotals[category] ?? 0) + amount;
    }

    String topCategory = "N/A";
    double maxAmount = 0;

    categoryTotals.forEach((category, amount) {
      if (amount > maxAmount) {
        maxAmount = amount;
        topCategory = category;
      }
    });

    pdf.addPage(
      pw.Page(

        // ✅ APPLY FONT TO PDF
        theme: pw.ThemeData.withFont(
          base: font,
        ),

        build: (pw.Context context) {

          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [

              pw.Text(
                "Expense Report",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 5),

              pw.Text(
                "Month: $monthName",
                style: const pw.TextStyle(fontSize: 16),
              ),

              pw.SizedBox(height: 20),

              pw.Text("Monthly Budget: ₹${monthlyBudget.toStringAsFixed(2)}"),
              pw.Text("Total Spent: ₹${totalSpent.toStringAsFixed(2)}"),

              pw.Text(
                "Savings: ₹${savings.toStringAsFixed(2)}",
                style: pw.TextStyle(
                  color: savings < 0 ? PdfColors.red : PdfColors.black,
                ),
              ),

              pw.SizedBox(height: 10),

              pw.Text("Total Transactions: $totalTransactions"),
              pw.Text("Top Spending Category: $topCategory"),
              pw.Text("Generated on: $generatedDate"),

              pw.SizedBox(height: 20),

              pw.Text(
                "Transactions",
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 10),

              pw.Table.fromTextArray(
                headers: ["Title", "Category", "Amount", "Date"],
                data: expenses.map((e) {

                  final date = (e['date'] as Timestamp).toDate();

                  return [
                    e['title'],
                    e['category'],
                    "₹${e['amount']}",
                    DateFormat('dd MMM yyyy').format(date)
                  ];

                }).toList(),
              ),

              pw.Spacer(),

              pw.Center(
                child: pw.Text(
                  "Generated by TrackMint an Expense Tracker",
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ),

            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
    );

  }
}